# Font Values
[font]
size = 12
[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

# Cursor Values
[cursor]
style = "Underline"  

# Color Values
[colors.primary]
background = "#0e0f13"
foreground = "#b4befe"
