# Font Values
[font]
size = 12
[font.bold]
family = "Fira Mono"
style = "bold"

[font.bold_italic]
family = "Fira Mono"
style = "Bold Italic"

[font.italic]
family = "Fira Mono"
style = "Italic"

[font.normal]
family = "Fira Mono"
style = "Regular"

# Cursor Values
[cursor]
style = "Underline"  

# Color Values
[colors.primary]
background = "#10101b"
foreground = "#b4befe"

[window]
opacity = 0.4
