#!/bin/bash

echo Clearing Cache...

yay -Scc --noconfirm

find ~/.cache -mindepth 1 -maxdepth 1 \
  ! -name "spotify" \
  ! -name "cliphist" \
  ! -name "yay" \
  ! -name "Hyprland Polkit Agent" \
  ! -name "spotube" \
  ! -name "oss.krtirtho.spotube" \
  -exec rm -rf {} +
echo Cache Cleared.

