#!/bin/bash

if [[ -d "dotfiles" ]]; then
    rm -rf dotfiles  # Remove the folder if it exists
fi

curl -sSL https://raw.githubusercontent.com/BinaryHarbinger/Dotfiles/refs/heads/main/install.sh | bash
