#!/bin/bash

CHECK=$(ls |grep dotfiles)

if [ -n "$CHECK" ]; then
	echo Deleting old files.
    rm -rf dotfiles  # Remove the folder if it exists
fi

curl -sSL https://raw.githubusercontent.com/BinaryHarbinger/Dotfiles/refs/heads/main/install.sh | bash
