#!/bin/bash

echo System Update
echo
echo "Enter your sudo password to update."
sudo echo >/dev/null 2>&1
echo "Updating Pacman Packages..."
yay --noconfirm >/dev/null 2>&1
echo "Clearing yay Cache..."
yay -Scc --noconfirm >/dev/null 2>&1
echo "Completed."
echo
echo "Updating Flatpaks..."
flatpak update
echo
echo Triming Disks..
sudo fstrim -Av >/dev/null 2>&1
echo
echo "Update completed."
